# Generated by Django 5.0.1 on 2024-03-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_coordinates_shot_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='club',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
