# Generated by Django 5.0.1 on 2024-03-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_coordinates_shot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
