# Generated by Django 5.0.1 on 2024-03-01 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_coordinates_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shot',
            name='end_latitude',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='end_longitude',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='hole_number',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='round',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='start_longitude',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='taken_at',
        ),
        migrations.RemoveField(
            model_name='shot',
            name='total_distance',
        ),
        migrations.AddField(
            model_name='shot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shot',
            name='shot_distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='shot',
            name='club',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
