# Generated by Django 5.0.1 on 2024-03-01 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_shot_end_latitude_remove_shot_end_longitude_and_more'),
        ('users', '0005_alter_clubs_id_alter_clubs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clubs'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
