# Generated by Django 5.0.1 on 2024-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_shot_club_delete_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shot',
            name='shot_distance',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
